# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mail2context',
                'doc_host': 'https://danieljelinko.github.io',
                'git_url': 'https://github.com/danieljelinko/mail2context',
                'lib_path': 'mail2context'},
  'syms': {'mail2context.core': {'mail2context.core.hello': ('core.html#hello', 'mail2context/core.py')}, 'mail2context.utils.my_test': {}}}
