"""Core functionality for mail2context"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['hello']

# %% ../nbs/00_core.ipynb #a5c66e8d
from fastcore.basics import *

# %% ../nbs/00_core.ipynb #c511ece1
def hello():
    "Say hello"
    return "Hello from mail2context!"
